# Github Workflow, set to run on push to Github

name: Code Checks
on: 
  push:
  pull_request:
  
jobs:
  tests:
    name: Check Python ${{ matrix.python-version }} on ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    continue-on-error: ${{ matrix.allow_failure }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        runs-on: ['ubuntu-latest']
        allow_failure: [false]

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
    - uses: astral-sh/setup-uv@v2
    
    - name: Set up Puthon ${{ matrix.python-version}}
    - run: uv python install ${{ matrix.python-version }}

    - name: Install virtual environment
    - run: uv venv

    - name: Install dependencies
    - run: uv sync -dev

    - name: Run tests
    - run: uv run coverage run -m pytest -m "not slow"
    - run: uv run coverage report --show-missing
